baseurl = "https://alexsdatascienceblog.netlify.com/"
languageCode = "de-DE"
title = "Alex's Data Science Blog"
theme = "hugo-lithium"
googleAnalytics = "UA-141455230-1"
disqusShortname = "alexsdatascienceblog"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "KI fü alle Channel"
    url = "https://www.youtube.com/channel/UCMfQpMewAT6yrglbOxLPDxA"

[params]
    description = "Alex's Data Science Blog"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "android-icon-144x144.png"
    width = 100
    height = 100
    alt = "android-icon-144x144"

